import express from 'express';
import { registerUser } from '../controllers/authController.js';
import { loginUser } from '../controllers/authController.js';
import { logoutUser } from '../controllers/authController.js';
import { adminLogin } from '../controllers/authController.js';
const authRoutes = express.Router();
authRoutes.post("/register", registerUser);
authRoutes.post("/login", loginUser);
authRoutes.post("/logout", logoutUser);
authRoutes.post("/admin/login", adminLogin);
export default authRoutes;