import express from 'express';
import { isAuth, registerUser } from '../controllers/authController.js';
import { loginUser } from '../controllers/authController.js';
import { logoutUser } from '../controllers/authController.js';
import { adminLogin } from '../controllers/authController.js';
import { getProfile } from '../controllers/authController.js';
import { protect } from '../middlewares/authMiddleware.js';
const authRoutes = express.Router();
authRoutes.post("/register", registerUser);
authRoutes.post("/login", loginUser);
authRoutes.post("/logout", logoutUser);
authRoutes.post("/admin/login", adminLogin);
authRoutes.get("/profile", protect, getProfile);
authRoutes.get("/is-auth", protect, isAuth);
export default authRoutes;